#!/bin/bash
# 14-serial-lock.sh
#
# Integration test for Finding 3 - serial file race in approve_request.
#
# Verifies that concurrent calls to Dispatcher::Pairing::approve_request
# produce certs with distinct serial numbers. The flock in approve_request
# serialises signing through ca.serial; without it two processes can read
# the same serial and produce duplicate certs.
#
# This test runs on the dispatcher host. It does not require a running agent
# or network access. It uses a temporary CA directory generated by openssl
# directly, bypassing the dispatcher CLI.
#
# Requires: openssl, Perl with Dispatcher::Pairing loadable (i.e. run from
# the dispatcher source tree or an installed dispatcher host).
#
# Skip conditions:
#   - openssl not available
#   - Dispatcher::Pairing cannot be loaded

set -uo pipefail
# This test requires no live agents. Set AGENT1 to suppress lib.sh's
# auto-discovery which would exit if no agents are registered.
AGENT1="${AGENT1:-none}"
source "${_LIB_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}/lib.sh"

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------

if ! command -v openssl >/dev/null 2>&1; then
    skip "openssl not available" "install openssl to run this test"
    summary
    exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/../../lib"

if ! perl -I"$LIB_DIR" -e 'use Dispatcher::Pairing qw()' 2>/dev/null; then
    skip "Dispatcher::Pairing not loadable" \
        "run from dispatcher source tree or installed host"
    summary
    exit 0
fi

# ---------------------------------------------------------------------------
# Setup: temporary CA directory and pairing queue
# ---------------------------------------------------------------------------

WORK_DIR=$(mktemp -d)
trap 'rm -rf "$WORK_DIR"' EXIT

CA_DIR="$WORK_DIR/ca"
PAIRING_DIR="$WORK_DIR/pairing"
mkdir -p "$CA_DIR" "$PAIRING_DIR"

# Generate a minimal test CA (2048-bit for speed)
openssl genrsa -out "$CA_DIR/ca.key" 2048 2>/dev/null
chmod 0600 "$CA_DIR/ca.key"
openssl req -new -x509 \
    -key "$CA_DIR/ca.key" \
    -out "$CA_DIR/ca.crt" \
    -days 1 \
    -subj '/CN=Test CA' \
    2>/dev/null
printf '01' > "$CA_DIR/ca.serial"

# Generate two test agent keys and CSRs
for i in 1 2; do
    openssl genrsa -out "$WORK_DIR/agent${i}.key" 2048 2>/dev/null
    openssl req -new \
        -key "$WORK_DIR/agent${i}.key" \
        -out "$WORK_DIR/agent${i}.csr" \
        -subj "/CN=test-agent-${i}" \
        2>/dev/null
done

CSR1=$(cat "$WORK_DIR/agent1.csr")
CSR2=$(cat "$WORK_DIR/agent2.csr")

# Write two pairing request queue files
REQID1="test0000000001"
REQID2="test0000000002"

perl -MDispatcher::Pairing -MJSON -e '
    my $csr = do { local $/; open my $f, "<", $ARGV[0] or die $!; <$f> };
    open my $fh, ">", $ARGV[1] or die $!;
    print $fh encode_json({
        hostname  => "test-agent-1",
        ip        => "127.0.0.1",
        csr       => $csr,
        nonce     => "aabbccddaabbccdd",
        received  => time(),
    });
' "$WORK_DIR/agent1.csr" "$PAIRING_DIR/${REQID1}.json"

perl -MDispatcher::Pairing -MJSON -e '
    my $csr = do { local $/; open my $f, "<", $ARGV[0] or die $!; <$f> };
    open my $fh, ">", $ARGV[1] or die $!;
    print $fh encode_json({
        hostname  => "test-agent-2",
        ip        => "127.0.0.1",
        csr       => $csr,
        nonce     => "1122334411223344",
        received  => time(),
    });
' "$WORK_DIR/agent2.csr" "$PAIRING_DIR/${REQID2}.json"

# ---------------------------------------------------------------------------
# Perl helper: approves one request and writes the resulting cert to a file
# ---------------------------------------------------------------------------

APPROVE_HELPER="$WORK_DIR/approve_one.pl"
cat > "$APPROVE_HELPER" << 'PERL'
#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin);

# Allow lib path to be passed as first arg before reqid
my ($lib_dir, $reqid, $ca_dir, $pairing_dir, $out_cert) = @ARGV;
unshift @INC, $lib_dir;

require Dispatcher::CA;
require Dispatcher::Pairing;
require Dispatcher::Log;
require Dispatcher::Registry;

Dispatcher::Log::init('test-serial-lock');

# Stub registry write - we only care about the cert serial
{
    no warnings 'redefine';
    *Dispatcher::Registry::register_agent = sub {};
}

eval {
    Dispatcher::Pairing::approve_request(
        reqid       => $reqid,
        ca_dir      => $ca_dir,
        pairing_dir => $pairing_dir,
    );
};
if ($@) {
    die "approve_request failed for $reqid: $@\n";
}

# Extract the cert from the .approved file and write it out
my $approved_file = "$pairing_dir/${reqid}.approved";
-f $approved_file or die "No approved file for $reqid\n";

require JSON;
my $resp = do { local $/; open my $f, '<', $approved_file or die $!; <$f> };
my $data = JSON::decode_json($resp);
open my $fh, '>', $out_cert or die "Cannot write $out_cert: $!\n";
print $fh $data->{cert};
close $fh;
PERL
chmod 0755, "$APPROVE_HELPER"

# ---------------------------------------------------------------------------
# Run two approvals concurrently 5 times and check for distinct serials
# ---------------------------------------------------------------------------

describe "concurrent approve_request calls produce distinct serial numbers"

ITERATIONS=5
COLLISION_COUNT=0

for i in $(seq 1 $ITERATIONS); do
    # Reset queue files for each iteration (serial advances each time - that's fine)
    cp "$WORK_DIR/agent1.csr" "$WORK_DIR/agent1_iter.csr"
    cp "$WORK_DIR/agent2.csr" "$WORK_DIR/agent2_iter.csr"

    # Re-write queue files (reqids are reused; .approved files are cleaned up below)
    perl -MDispatcher::Pairing -MJSON -e '
        my $csr = do { local $/; open my $f, "<", $ARGV[0] or die $!; <$f> };
        open my $fh, ">", $ARGV[1] or die $!;
        print $fh JSON::encode_json({
            hostname => "test-agent-1",
            ip       => "127.0.0.1",
            csr      => $csr,
            nonce    => "aabbccddaabbccdd",
            received => time(),
        });
    ' "$WORK_DIR/agent1.csr" "$PAIRING_DIR/${REQID1}.json"

    perl -MDispatcher::Pairing -MJSON -e '
        my $csr = do { local $/; open my $f, "<", $ARGV[0] or die $!; <$f> };
        open my $fh, ">", $ARGV[1] or die $!;
        print $fh JSON::encode_json({
            hostname => "test-agent-2",
            ip       => "127.0.0.1",
            csr      => $csr,
            nonce    => "1122334411223344",
            received => time(),
        });
    ' "$WORK_DIR/agent2.csr" "$PAIRING_DIR/${REQID2}.json"

    rm -f "$PAIRING_DIR/${REQID1}.approved" "$PAIRING_DIR/${REQID2}.approved"

    CERT1="$WORK_DIR/cert1_iter${i}.pem"
    CERT2="$WORK_DIR/cert2_iter${i}.pem"

    # Fork two approvals simultaneously
    perl -I"$LIB_DIR" "$APPROVE_HELPER" "$LIB_DIR" "$REQID1" "$CA_DIR" "$PAIRING_DIR" "$CERT1" &
    PID1=$!
    perl -I"$LIB_DIR" "$APPROVE_HELPER" "$LIB_DIR" "$REQID2" "$CA_DIR" "$PAIRING_DIR" "$CERT2" &
    PID2=$!

    FAIL1=0; FAIL2=0
    wait $PID1 || FAIL1=1
    wait $PID2 || FAIL2=1

    if [ "$FAIL1" -eq 1 ] || [ "$FAIL2" -eq 1 ]; then
        fail "iteration $i: one or both approve_request calls failed"
        continue
    fi

    if [ ! -f "$CERT1" ] || [ ! -f "$CERT2" ]; then
        fail "iteration $i: cert file(s) not produced"
        continue
    fi

    SERIAL1=$(openssl x509 -noout -serial -in "$CERT1" 2>/dev/null | cut -d= -f2)
    SERIAL2=$(openssl x509 -noout -serial -in "$CERT2" 2>/dev/null | cut -d= -f2)

    if [ -z "$SERIAL1" ] || [ -z "$SERIAL2" ]; then
        fail "iteration $i: could not extract serial from cert(s)" \
            "serial1='$SERIAL1' serial2='$SERIAL2'"
        continue
    fi

    if [ "$SERIAL1" = "$SERIAL2" ]; then
        COLLISION_COUNT=$((COLLISION_COUNT + 1))
        fail "iteration $i: serial collision detected" \
            "both certs have serial $SERIAL1"
    else
        pass "iteration $i: distinct serials ($SERIAL1 vs $SERIAL2)"
    fi
done

# Summary assertion: zero collisions across all iterations
if [ "$COLLISION_COUNT" -eq 0 ]; then
    pass "no serial collisions in $ITERATIONS concurrent approval pairs"
else
    fail "serial collisions detected" \
        "$COLLISION_COUNT of $ITERATIONS iterations produced duplicate serials"
fi

summary
